# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: statia_db_container
    restart: always
    environment:
      POSTGRES_USER: user_tobias
      POSTGRES_PASSWORD: password_segura
      POSTGRES_DB: tobias_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: